"""initial

Revision ID: 139e8c894c3
Revises: 51f5ccfba190
Create Date: 2014-09-09 19:10:24.941093

"""

# revision identifiers, used by Alembic.
revision = '139e8c894c3'
down_revision = '51f5ccfba190'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
