"""empty message

Revision ID: 40528ebe9959
Revises: 476bf43a6e2f
Create Date: 2014-09-09 14:29:44.041129

"""

# revision identifiers, used by Alembic.
revision = '40528ebe9959'
down_revision = '476bf43a6e2f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
