"""empty message

Revision ID: 47b4ac7d7d6e
Revises: 57b811035a20
Create Date: 2014-09-09 20:26:07.166443

"""

# revision identifiers, used by Alembic.
revision = '47b4ac7d7d6e'
down_revision = '57b811035a20'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
