"""empty message

Revision ID: 4823c645237c
Revises: 1b966e7f4b9e
Create Date: 2014-09-05 12:56:04.642525

"""

# revision identifiers, used by Alembic.
revision = '4823c645237c'
down_revision = '1b966e7f4b9e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('body_html', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'body_html')
    ### end Alembic commands ###
