"""empty message

Revision ID: 57b811035a20
Revises: 139e8c894c3
Create Date: 2014-09-09 20:18:35.583311

"""

# revision identifiers, used by Alembic.
revision = '57b811035a20'
down_revision = '139e8c894c3'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
