"""empty message

Revision ID: f03b0edbfab
Revises: 570fce378adf
Create Date: 2014-09-05 17:02:40.792927

"""

# revision identifiers, used by Alembic.
revision = 'f03b0edbfab'
down_revision = '570fce378adf'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
